name: main - Update Projects
run-name: >
  ${{
    github.event.action == 'main_update_all' && 'All Projects' ||
    github.event.action == 'main_update_post' && github.event.client_payload.rel_path ||
    ''
  }}

permissions:
  id-token: write
  contents: write

on:
  repository_dispatch:
    types:
      - main_update_all
      - main_update_post
  push:
    branches:
      - main
    paths-ignore:
      - Models/**

jobs:
  deploy:
    runs-on: windows-2025
    steps:
      - name: Install Pipeline Package
        shell: pwsh
        run: |
          git clone https://x-token-auth:${{ secrets.STARTER_PROJECTS_PIPELINE_TOKEN }}@bitbucket.org/imagimob/starter-projects-pipeline.git
          pip install -e starter-projects-pipeline

      - name: Update projects
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENSOR_MAP: ${{ vars.SENSOR_MAP }}
          STARTER_PROJECTS_PIPELINE_TOKEN: ${{ secrets.STARTER_PROJECTS_PIPELINE_TOKEN }}
        run: |
          if ("${{ github.event.action }}" -eq "main_update_all") {
            $args = @()
            if ('${{ toJson(github.event.client_payload) }}' -ne 'null') { $args += "--version", "${{ github.event.client_payload.version }}", "--commit", "${{ github.event.client_payload.commit }}" }
            dcp update-all @args
          } elseif ("${{ github.event.action }}" -eq "main_update_post") {
            dcp update-trained --project '${{ toJson(github.event.client_payload) }}'
          } elseif ("${{ github.event_name }}" -eq "push") {
            dcp update-changes --commit '${{ github.sha }}'
          } else {
            throw "Unsupported event: ${{ github.event_name }}"
          }
